# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('Message', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
    ]
