# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtest', '0004_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Number',
            field=models.CharField(max_length=10),
        ),
    ]
